name: Docs

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme

      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Init new repo in dist folder and commit
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global init.defaultBranch main
          cd docs/build/html/
          git init
          touch .nojekyll
          echo 'cli.ablestar.com' > CNAME
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ls -al .
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
